PREFIX saref: <https://saref.etsi.org/core/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX s4city: <https://saref.etsi.org/saref4city/>
PREFIX usage-o: <http://w3id.org/def/usage#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
# Query to be run on top of USAGE-ZGZ-District-level repository (w.o cells data)
select distinct ?district ?districtName ?sector ?intervalYear ?kpi ?kpiLabel ?kpiaValue ?districtGeometryWKT  where { 
    ?kpia a s4city:KeyPerformanceIndicatorAssessment;
#          a ?kpiaType;
          saref:hasValue ?kpiaValue;
#          saref:isMeasuredIn ?kpiaValueUnit;
          s4city:quantifiesKPI ?kpi;
          s4city:refersToFeature ?district;
          s4city:refersToTime ?interval;          
          usage-o:refersToSector ?sector.
    ?kpi a s4city:KeyPerformanceIndicator;
#         a ?kpiType;
         rdfs:label ?kpiLabel;
         rdfs:comment ?kpiComment.
    OPTIONAL{?sector a usage-o:Sector;
#            a ?sectorType;
            rdfs:label ?sectorLabel;
            rdfs:comment ?sectorComment.}
    OPTIONAL{?sector skos:broader ?sectorBroader.
    		?sectorBroader a ?sectorBroaderType;
                     rdfs:label ?sectorBroaderLabel;
                     rdfs:comment ?sectorBroaderComment.}
    ?interval a time:DateTimeInterval;
#              a ?intervalType;
              time:hasDateTimeDescription ?intervalDescription.
    ?intervalDescription a time:DateTimeDescription;
                         a ?intervalDescriptionType;
                         time:year ?intervalYear.
#    ?kpiaValueUnit a saref:UnitOfMeasure.
    
    ?district a s4city:District;
#              a ?districtType;
              rdfs:label ?districtName.
#    OPTIONAL{?district owl:sameAs ?otherSourceDistrict.}
    OPTIONAL{?district geo:hasGeometry ?districtGeometry.
    		 ?districtGeometry a geo:Geometry; 
#                         a ?districtGeometryType;
                         geo:asWKT ?districtGeometryWKT}
    FILTER REGEX (str(?district), "http://w3id.org/def/usage/resource/District/ZGZ-id-", "i")

}